apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: w255
  labels:
    app: redis
spec:
  replicas: 1 # A single replica is often used for simple caching
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests: 
            memory: "128Mi"
            cpu: "100m"
           
