apiVersion: v1
kind: Service
metadata: 
  name: prediction-service
  namespace: w255
  labels:
    app: housing-label
spec:
  type: LoadBalancer
  selector:
    app: housing-label
  ports:
    - port: 8000
      targetPort: 8000 ### this is the one defined in api-deployment AND Dockerfile

